-- 코드를 입력하세요
SELECT b.TITLE, r.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, TO_CHAR(r.CREATED_DATE, 'YYYY-mm-DD') as CREATED_DATE 
FROM USED_GOODS_BOARD b 
JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID  
WHERE TO_CHAR(b.CREATED_DATE, 'YYYYmm') = '202210' 
ORDER BY TO_CHAR(r.CREATED_DATE, 'YYYY-mm-DD') ASC, b.TITLE ASC;